{
 "title": "Basic Dashboard Example",
 "time": { "from": "2019-05-21T22:44:34.455Z", "to": "2019-05-21T23:01:49.318Z" },
 "panels": [
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "measurement": "proc_meminfo",
     "select": [
      [
       { "params": [ "MemAvailable" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "proc_meminfo",
     "select": [
      [
       { "params": [ "Cached" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Server Load Avg",
   "type": "graph",
   "gridPos": { "h": 9, "w": 10, "x": 14, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "measurement": "proc_loadavg",
     "select": [
      [
       { "params": [ "load_avg_1min" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "proc_loadavg",
     "select": [
      [
       { "params": [ "load_avg_5min" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "proc_loadavg",
     "select": [
      [
       { "params": [ "load_avg_15min" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPUs Baremetal",
   "type": "graph",
   "gridPos": { "h": 10, "w": 14, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "measurement": "stat_cpu0",
     "select": [
      [
       { "params": [ "user" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "stat_cpu1",
     "select": [
      [
       { "params": [ "user" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "stat_cpu2",
     "select": [
      [
       { "params": [ "user" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "stat_cpu3",
     "select": [
      [
       { "params": [ "user" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Network Bytes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 10, "x": 14, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "network_interfaces_enp3s0",
     "select": [
      [
       { "params": [ "ibytes" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "network_interfaces_enp3s0",
     "select": [
      [
       { "params": [ "obytes" ], "type": "field" }
      ]
     ]
    }
   ]
  }
 ]
}